from dataclasses import dataclass, field
from fractions import Fraction
from numbers import Real
from typing import Any

from ._exact_linear_algebra import ExactSquareMatrix
from .remesh_history_stability import UniformRemeshHistoryStabilityCertificate
from .remesh_schedule_policy_stability import (
    UniformRemeshSchedulePolicyStabilityCertificate,
)

@dataclass(frozen=True, slots=True)
class UniformRemeshScheduleRelativeDefectStabilityCertificate:
    policy_certificate: UniformRemeshSchedulePolicyStabilityCertificate = field(...)
    pre_schedule_relative_energy_defect_upper_bound: Fraction
    exact_effective_head_energy_gain_upper_bound: Fraction
    effective_head_gain_envelope_certificate: (
        UniformRemeshSchedulePolicyStabilityCertificate
    ) = field(...)
    conditions: tuple[tuple[str, bool], ...]
    _proof_stamp: tuple[Any, ...] = field(...)
    def _proof_fields_are_intact(self) -> bool: ...
    @property
    def scope(self) -> str: ...
    @property
    def relative_defect_stability_certificate_certified(self) -> bool: ...
    @property
    def failed_conditions(self) -> tuple[str, ...]: ...
    @property
    def remesh_certificate(self) -> UniformRemeshHistoryStabilityCertificate: ...
    @property
    def schedule_energy_gain_upper_bound(self) -> Fraction: ...
    @property
    def effective_head_energy_gain_upper_bound(self) -> Fraction: ...
    @property
    def history_length(self) -> int: ...
    @property
    def universal_block_horizon(self) -> int: ...
    @property
    def remesh_companion_matrix(self) -> ExactSquareMatrix: ...
    @property
    def effective_head_energy_domination_matrix(self) -> ExactSquareMatrix: ...
    @property
    def remesh_block_power(self) -> ExactSquareMatrix: ...
    @property
    def effective_head_block_domination_power(self) -> ExactSquareMatrix: ...
    @property
    def exact_uniform_normalized_block_margin_lower_bound(self) -> Fraction: ...
    @property
    def exact_uniform_block_energy_gain_upper_bound(self) -> Fraction: ...
    @property
    def exact_intrablock_prefix_energy_gain_upper_bound(self) -> Fraction: ...
    @property
    def conditional_exact_model_spatial_disagreement_nonincrease_certified(
        self,
    ) -> bool: ...
    @property
    def uniform_intrablock_prefix_bound_certified(self) -> bool: ...
    @property
    def uniform_positive_normalized_block_margin_certified(self) -> bool: ...
    @property
    def repeated_exact_model_spatial_disagreement_stability_certified(
        self,
    ) -> bool: ...
    @property
    def geometric_spatial_disagreement_convergence_certified(self) -> bool: ...
    @property
    def q_zero_preschedule_defect_absorption_certified(self) -> bool: ...
    @property
    def effective_gain_one_zero_margin_boundary_certified(self) -> bool: ...
    def exact_cycle_energy_gain_upper_bound(self, cycle_count: int) -> Fraction: ...
    @property
    def runtime_relative_defect_bound_verified(self) -> bool: ...
    @property
    def runtime_schedule_maps_verified(self) -> bool: ...
    @property
    def runtime_forward_invariance_certified(self) -> bool: ...
    @property
    def future_runtime_stability_certified(self) -> bool: ...
    @property
    def binary64_runtime_stability_certified(self) -> bool: ...
    @property
    def solver_accuracy_certified(self) -> bool: ...
    @property
    def solver_order_certified(self) -> bool: ...
    @property
    def adaptive_grammar_certified(self) -> bool: ...
    @property
    def full_tnfr_stability_certified(self) -> bool: ...

def certify_uniform_remesh_schedule_relative_defect_stability(
    policy_certificate: UniformRemeshSchedulePolicyStabilityCertificate,
    pre_schedule_relative_energy_defect_upper_bound: Real,
) -> UniformRemeshScheduleRelativeDefectStabilityCertificate: ...

__all__: tuple[str, ...]
