from typing import Any

__all__: Any

def __getattr__(name: str) -> Any: ...

ALL_OPERATOR_NAMES: Any
AUTOORGANIZACION: Any
AUTOORGANIZACION_CIERRES: Any
CANONICAL_NAME_BY_ALIAS: Any
CANONICAL_OPERATOR_NAMES: Any
CIERRE_VALIDO: Any
COHERENCE: Any
CONTRACTION: Any
COUPLING: Any
DISSONANCE: Any
EMISSION: Any
ENGLISH_OPERATOR_NAMES: Any
EXPANSION: Any
INICIO_VALIDOS: Any
MUTATION: Any
RECEPTION: Any
RECURSIVITY: Any
RESONANCE: Any
SELF_ORGANIZATION: Any
SILENCE: Any
SPANISH_OPERATOR_NAMES: Any
SPANISH_TO_ENGLISH: Any
TRAMO_INTERMEDIO: Any
TRANSITION: Any
canonical_operator_name: Any
operator_display_name: Any
ACOPLAMIENTO: Any
AUTOORGANIZACION: Any
COHERENCIA: Any
CONTRACCION: Any
DISONANCIA: Any
EMISION: Any
EXPANSION_ES: Any
MUTACION: Any
RECEPCION: Any
RECURSIVIDAD: Any
RESONANCIA: Any
SILENCIO: Any
TRANSICION: Any
