from typing import Any

__all__: Any

def __getattr__(name: str) -> Any: ...

ACOPLAMIENTO: Any
ALL_OPERATOR_NAMES: Any
AUTOORGANIZACION: Any
AUTOORGANIZACION_CIERRES: Any
CIERRE_VALIDO: Any
COHERENCIA: Any
CONTRACCION: Any
DISONANCIA: Any
EMISION: Any
EXPANSION: Any
INICIO_VALIDOS: Any
MUTACION: Any
RECEPCION: Any
RECURSIVIDAD: Any
RESONANCIA: Any
SILENCIO: Any
TRAMO_INTERMEDIO: Any
TRANSICION: Any
