#!/usr/bin/env python3
"""
Example 131 — Finite Co-Emergent REMESH Loop Survey
===================================================

The emergent-geometry arc (examples 123-130) measured the BASE, the FIBER, and
their COUPLING separately, and showed (example 128) that closing the loop
topology -> substrate -> topology with the MST REMESH mode reaches a fixed
point for one fixture. This example treats the CLOSED loop as a coupled map and
classifies its finite traces under selected deterministic REMESH settings.

The surveyed loop
-----------------
    topology T
      --(nodal equation: evolve EPI on T)-->  substrate (EPI field)
      --(apply_topological_remesh, mode in {mst, knn, community})-->  T'
      -->  repeat

The EPI channel follows an explicit Euler discretization of the nodal equation;
the topology is regenerated by ``apply_topological_remesh``. ``p_rewire = 0``
removes injected rewiring randomness, so each seeded run is deterministic.

Measured finite outcomes
------------------------
The default fixture reaches a fixed edge set for ``mst``, ``knn``, and
``community``. A separate 72-run sweep covers only ``mst`` and ``knn`` over 12
seeds and three sizes: all 36 MST traces become fixed; 34/36 kNN traces become
fixed and 2/36 remain near-fixed within the observation window. No classified
cycle or disconnected-graph divergence occurs in that finite sample.

Three measured results
----------------------
M1 DEFAULT-FIXTURE OUTCOMES. ``mst``, ``knn``, and ``community`` reach fixed
   edge sets for ``n=16`` and ``seed=0``, with mode-dependent structure.

M2 FINITE-SWEEP CLASSIFICATION. Sweeping ``mst`` and ``knn`` across 12 seeds x
   3 sizes gives the counts above. ``community`` is not included in this sweep.
   A near-fixed label is observational: it does not establish eventual
   convergence or rule out a longer-period orbit.

M3 U2 VOCABULARY, WITHOUT A U2 CERTIFICATE. The sampled traces can be compared
   with U2's boundedness motivation, but this experiment neither integrates an
   infinite-time ``nu_f*dNFR`` tail nor validates an operator history. Moreover,
   the changing graph lies outside a fixed-graph diffusion theorem. It therefore
   does not prove that U2 lifts to the coupled map.

Honest scope
------------
A reproducible finite survey of one Euler step size, one EPI-only weighting,
one initial topology family, three default probes, and a two-mode parameter
sweep. The experiment supplies counterexample-search evidence within that
domain. It proves no universal convergence statement, no U2 inheritance, and
no result about open mathematical problems.

References
----------
- src/tnfr/operators/remesh.py (apply_topological_remesh: mst/knn/community)
- src/tnfr/dynamics/dnfr.py (the canonical dNFR / nodal equation)
- examples/08_emergent_geometry/128_base_substrate_coemergence.py (the MST fixed point)
- examples/08_emergent_geometry/129_spectral_gap_base_fiber_clock.py (lambda_2 of the tree)
- AGENTS.md "U2: CONVERGENCE & BOUNDEDNESS", "Transport Content of the Nodal Equation"
"""

import math
import os
import sys
import warnings

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))

import networkx as nx
import numpy as np

from tnfr.alias import get_attr, set_attr
from tnfr.constants import inject_defaults
from tnfr.constants.aliases import ALIAS_DNFR, ALIAS_EPI, ALIAS_VF
from tnfr.dynamics import default_compute_delta_nfr
from tnfr.operators.remesh import apply_topological_remesh
from tnfr.physics.structural_diffusion import structural_eigenmodes
from tnfr.physics.symplectic_substrate import (
    extract_phase_space_point,
    substrate_hamiltonian,
)


def _seed_state(G, rng):
    for nd in G.nodes():
        G.nodes[nd]["theta"] = float(rng.uniform(0, 2 * math.pi))
        set_attr(G.nodes[nd], ALIAS_EPI, float(rng.uniform(-0.5, 0.5)))
        set_attr(G.nodes[nd], ALIAS_VF, 1.0)


def _evolve_epi(G, steps, dt=0.1):
    G.graph["DNFR_WEIGHTS"] = {"epi": 1.0, "phase": 0, "vf": 0, "topo": 0}
    for _ in range(steps):
        default_compute_delta_nfr(G)
        for nd in G.nodes():
            e = get_attr(G.nodes[nd], ALIAS_EPI, 0.0)
            v = get_attr(G.nodes[nd], ALIAS_VF, 0.0)
            d = get_attr(G.nodes[nd], ALIAS_DNFR, 0.0)
            set_attr(G.nodes[nd], ALIAS_EPI, e + dt * v * d)


def _norm_edges(G):
    return frozenset(tuple(sorted(e)) for e in G.edges())


def _jaccard(a, b):
    if not a and not b:
        return 1.0
    return len(a & b) / len(a | b)


def _run_loop(mode, n=16, n_iter=25, evolve_steps=3, seed=0, k=3):
    """Run one deterministic finite REMESH-loop fixture and return its trace."""
    rng = np.random.default_rng(seed)
    G = nx.cycle_graph(n)
    inject_defaults(G)
    G.graph["RANDOM_SEED"] = seed
    _seed_state(G, rng)
    edges, hsub, lam2 = [], [], []
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        for _ in range(n_iter):
            _evolve_epi(G, evolve_steps)
            apply_topological_remesh(G, mode=mode, k=k, p_rewire=0.0, seed=seed)
            edges.append(_norm_edges(G))
            for nd in G.nodes():
                set_attr(G.nodes[nd], ALIAS_VF, 1.0)
            p = extract_phase_space_point(G)
            hsub.append(substrate_hamiltonian(p))
            if nx.is_connected(G) and G.number_of_nodes() > 1:
                ev, _ = structural_eigenmodes(G)
                lam2.append(float(ev[1]) if len(ev) > 1 else 0.0)
            else:
                lam2.append(float("nan"))
    return edges, hsub, lam2


def experiment_1_modes():
    """M1: classify one default fixture for each available REMESH mode."""
    print("=" * 74)
    print("EXPERIMENT 1: Default-Fixture Outcomes by REMESH Mode")
    print("=" * 74)
    print("Close the loop with each canonical mode; classify the asymptotic")
    print("regime and characterize the fixed point (H_sub, lambda_2).")
    print()
    print(
        f"  {'mode':>10} {'regime':>14} {'H_sub*':>9} {'lambda_2*':>10} "
        f"{'structure':>22}"
    )
    structure = {
        "mst": "spanning tree",
        "knn": "tree + kNN EPI edges",
        "community": "EPI-community collapse",
    }
    for mode in ["mst", "knn", "community"]:
        edges, hsub, lam2 = _run_loop(mode)
        js = [_jaccard(edges[i], edges[i + 1]) for i in range(len(edges) - 1)]
        tail = js[-5:]
        if all(j > 0.999 for j in tail):
            regime = "FIXED POINT"
        elif max(tail) - min(tail) > 0.05:
            regime = "CYCLE"
        else:
            regime = "near-fixed"
        print(
            f"  {mode:>10} {regime:>14} {hsub[-1]:>9.2f} {lam2[-1]:>10.3f} "
            f"{structure[mode]:>22}"
        )
    print()
    print("  -> in this default fixture all three modes reach a FIXED POINT,")
    print("     with mode-dependent")
    print("     structure: mst = tree (smallest gap), knn = tree + edges,")
    print("     community = collapse onto EPI communities (aggressive).")


def experiment_2_robustness():
    """M2: report classifications for a finite mst/knn sweep."""
    print()
    print("=" * 74)
    print("EXPERIMENT 2: Finite mst/knn Sweep")
    print("=" * 74)
    print("Sweep mst and knn across 12 seeds x 3 sizes (36 runs each); classify")
    print("every asymptotic regime.")
    print()
    print(
        f"  {'mode':>6} {'fixed':>7} {'cycle':>6} {'diverge':>8} "
        f"{'near-fixed':>11} {'mean iters':>11}"
    )
    for mode in ["mst", "knn"]:
        n_fixed = n_cycle = n_div = n_near = 0
        iters = []
        for sd in range(12):
            for n in [10, 16, 22]:
                edges, _, lam2 = _run_loop(mode, n=n, n_iter=40, seed=sd)
                js = [_jaccard(edges[i], edges[i + 1]) for i in range(len(edges) - 1)]
                tail = js[-8:]
                diverged = any(math.isnan(x) for x in lam2[-3:])
                if diverged:
                    n_div += 1
                elif all(j > 0.999 for j in tail):
                    n_fixed += 1
                    first = next(
                        (
                            i
                            for i in range(len(edges) - 1)
                            if all(edges[m] == edges[i] for m in range(i, len(edges)))
                        ),
                        len(edges),
                    )
                    iters.append(first)
                elif max(tail) - min(tail) > 0.1:
                    n_cycle += 1
                else:
                    n_near += 1
        mean_it = np.mean(iters) if iters else float("nan")
        print(
            f"  {mode:>6} {n_fixed:>7} {n_cycle:>6} {n_div:>8} "
            f"{n_near:>11} {mean_it:>11.1f}"
        )
    print()
    print("  -> within these 72 finite traces: zero classified cycles and zero")
    print("     disconnected-graph divergences. Two knn traces remain near-fixed")
    print("     at the horizon; that label does not determine their asymptotics.")


def experiment_3_u2_link():
    """M3: compare one finite trace with U2 vocabulary without certifying U2."""
    print()
    print("=" * 74)
    print("EXPERIMENT 3: Selected Trace and the Limits of the U2 Comparison")
    print("=" * 74)
    print("U2 is motivated by convergence of the nodal integral of nu_f*dNFR.")
    print("This finite trace records neither its infinite-time tail nor a grammar")
    print("history, and the graph changes between diffusion segments.")
    print()
    edges, hsub, lam2 = _run_loop("knn", n=16, n_iter=20)
    print("  knn loop (n=16): the substrate energy and the base gap settle:")
    print(f"  {'iter':>5} {'H_sub':>9} {'lambda_2':>10} {'Jaccard step':>13}")
    js = [1.0] + [_jaccard(edges[i - 1], edges[i]) for i in range(1, len(edges))]
    for i in [0, 2, 5, 10, 15, 19]:
        print(f"  {i:>5} {hsub[i]:>9.3f} {lam2[i]:>10.3f} {js[i]:>13.3f}")
    print()
    print("  -> over this horizon H_sub and lambda_2 settle and the edge set")
    print("     stops changing. This is finite fixed-trace evidence; it is not")
    print("     a U2 certificate or a theorem for the coupled map.")


def main():
    print()
    print("  TNFR Example 131: Finite Co-Emergent REMESH Loop Survey")
    print("  ========================================================")
    print()
    experiment_1_modes()
    experiment_2_robustness()
    experiment_3_u2_link()
    print()
    print("=" * 74)
    print("WHAT THIS FINITE SURVEY ESTABLISHES")
    print("=" * 74)
    print("For n=16 and seed=0, mst, knn, and community reach fixed edge sets.")
    print("In the separate 72-run mst/knn sweep, all mst traces and 34/36 knn")
    print("traces become fixed; two knn traces remain near-fixed at the finite")
    print("horizon. No run is classified as a cycle or disconnected divergence.")
    print("Community is not part of that sweep. These observations do not prove")
    print("eventual convergence, exclude longer transients, or lift U2 to the")
    print("changing-topology map. The experiment is a reproducible bounded-domain")
    print("survey and closes no open problem.")


if __name__ == "__main__":
    main()
