"""Compare three structurally distinct read-outs without identifying them.

* Arithmetic pressure is an exact but divisibility-informed primality
  re-expression.
* The chemical example combines a chosen S² graph, conventional shell
  capacities, Madelung ordering and duet/octet closure rules.
* The loop example measures winding on explicitly prepared phase rings.

The first two reuse a numerical zero-pressure predicate, while winding is a
different topological invariant. Shared notation does not make their state
spaces or dynamics equivalent. This example demonstrates the implemented
calculations and their assumptions; it does not derive chemistry, quantum
mechanics or particle species from the nodal equation.

Run:
    python examples/07_number_theory/emergent_chemistry_particles_demo.py
"""

from __future__ import annotations

import sys

from tnfr.physics.emergent_chemistry import (
    classify_element,
    emergent_magic_numbers,
    fibonacci_sphere_graph,
    structural_eigenmodes,
)

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8")
from tnfr.physics.emergent_particles import (
    classify_winding_sector,
    winding_number,
    winding_ring,
)

try:
    import sympy as _sp

    from tnfr.mathematics.number_theory import ArithmeticStructuralTerms
    from tnfr.mathematics.number_theory import ArithmeticTNFRFormalism as _NT
    from tnfr.mathematics.number_theory import ArithmeticTNFRParameters

    _HAS_NT = True
except (ImportError, ModuleNotFoundError):  # pragma: no cover - optional cross-check
    _HAS_NT = False


def _rule(title: str) -> None:
    print("\n" + "=" * 72)
    print(title)
    print("=" * 72)


def demo_number_theory_anchor() -> None:
    """Comparison anchor: arithmetic primality as ΔNFR = 0."""
    _rule("COMPARISON — arithmetic primality as ΔNFR = 0")
    if not _HAS_NT:
        print("  (sympy/number_theory unavailable; skipping anchor)")
        return
    params = ArithmeticTNFRParameters()
    print(
        "  Canonical unit coefficients: "
        f"ζ={params.zeta:.4f}  η={params.eta:.4f}  θ={params.theta:.4f}"
    )
    print("  n   ΔNFR(n)   prime?")
    for n in (17, 15, 8, 30):
        terms = ArithmeticStructuralTerms(
            tau=int(_sp.divisor_count(n)),
            sigma=int(_sp.divisor_sigma(n)),
            omega=sum(e for _p, e in _sp.factorint(n).items()),
        )
        dnfr = _NT.delta_nfr_value(n, terms, params)
        print(f"  {n:<3d} {dnfr:7.4f}   {bool(_sp.isprime(n))}")
    print("  → ΔNFR = 0 on these primes; the calculation consumes Ω, τ and σ.")


def demo_chemistry() -> None:
    """Run the assumption-explicit shell-model correspondence."""
    _rule("CHEMICAL SHELL MODEL — assumptions plus graph-spectrum comparison")

    print("\nSTEP 1 — measured clusters on a constructed S² nearest-neighbour graph")
    G = fibonacci_sphere_graph(n_points=400, k_neighbors=6)
    shells = structural_eigenmodes(G)
    for s in shells:
        angular = (
            f"l={s.angular_index}; candidate 2l+1={s.multiplicity}"
            if s.angular_index is not None
            else f"unresolved angular label; multiplicity={s.multiplicity}"
        )
        print(
            f"  {angular}   eigenvalue = {s.eigenvalue:.4f}"
        )
    print(
        f"  → measured multiplicities {[s.multiplicity for s in shells]} "
        "under this finite clustering protocol"
    )

    print("\nSTEP 2 — closures generated by assumed capacities and Madelung ordering")
    print(f"  shell-model closure counts: {emergent_magic_numbers()}")
    print("  comparison values: [2, 10, 18, 36, 54, 86, 118]")

    print("\nSTEP 3 — selected duet/octet distance reported as ΔNFR_chem")
    samples = {
        1: "H",
        2: "He",
        3: "Li",
        6: "C",
        8: "O",
        9: "F",
        10: "Ne",
        11: "Na",
        17: "Cl",
        18: "Ar",
        36: "Kr",
        54: "Xe",
    }
    print("   Z  el  valence  ΔNFR_chem   status")
    for Z, name in samples.items():
        e = classify_element(Z)
        status = "model-closed" if e.closed_shell else "model-open"
        print(
            f"  {Z:>3d} {name:<3s}   {e.valence_electrons:>2d}     "
            f"{e.delta_nfr:7.4f}   {status}"
        )
    nobles_ok = all(classify_element(z).closed_shell for z in (2, 10, 18, 36, 54))
    print(f"  → listed closed-shell cases have model ΔNFR_chem = 0: {nobles_ok}")
    print("  → the assumed distance assigns selected neighbouring cases |ΔNFR| = 1")


def demo_particles() -> None:
    """Measure winding sectors on prepared phase rings."""
    _rule("CLOSED PHASE LOOPS — winding-sector measurement")

    print("\nWrapped circulation on explicitly prepared rings")
    print("  target   n=37   n=128   n=501   (measured winding W)")
    for target in (0.0, 1.0, 2.0, 3.0, -1.0, 1.5):
        ws = [winding_number(winding_ring(n, target))[0] for n in (37, 128, 501)]
        note = (
            "  ← sampled loop maps this real target to an integer class"
            if target == 1.5
            else ""
        )
        print(f"  {target:+.1f}     {ws[0]:+d}      {ws[1]:+d}      {ws[2]:+d}{note}")

    print("\nStructural winding-sector read-out")
    print("   W   orientation  class")
    for target in (0.0, 1.0, -1.0, 2.0, 3.0):
        sector = classify_winding_sector(winding_ring(240, target))
        orientation = {
            1: "positive",
            -1: "negative",
            0: "neutral",
        }[sector.orientation_sign]
        print(f"  {sector.winding:+d}   {orientation:<10s}  {sector.winding_class}")
    print("  → zero, unit and higher winding; sign records loop orientation")


def main() -> None:
    print(__doc__)
    demo_number_theory_anchor()
    demo_chemistry()
    demo_particles()
    _rule("SUMMARY")
    print("  Three scoped read-outs:")
    print("    primality   : ΔNFR(n) = 0")
    print("    noble gas   : ΔNFR_chem(Z) = 0")
    print("    phase loop  : wrapped winding W ∈ ℤ for a declared closed loop")
    print("  The chemical rules and loop initial conditions are explicit inputs.")


if __name__ == "__main__":
    main()
