name: Format Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  pre-commit:
    name: Python 3.11 format check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit

      - name: Run formatting hooks (black, isort)
        run: SKIP=pydocstyle pre-commit run --all-files

      - name: Run docstring check (pydocstyle)
        run: pre-commit run --all-files pydocstyle
