name: Type Check

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  static-analysis:
    name: Python 3.11 static analysis
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/src
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[test,typecheck]

      - name: Run flake8
        run: python -m flake8 src

      - name: Run pydocstyle
        run: python -m pydocstyle --add-ignore=D202 src/tnfr/selector.py src/tnfr/utils/data.py src/tnfr/utils/graph.py

      - name: Run mypy
        run: python -m mypy src/tnfr

      - name: Run vulture
        run: python -m vulture --min-confidence 80 src tests
        continue-on-error: true
